// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1jIA3Uw6Nr0YZavhlqbGJll1Z_LyhR4',
    appId: '1:1028662830128:web:3170889d38622d14b979f5',
    messagingSenderId: '1028662830128',
    projectId: 'app-explora-cdmx',
    authDomain: 'app-explora-cdmx.firebaseapp.com',
    storageBucket: 'app-explora-cdmx.firebasestorage.app',
    measurementId: 'G-EKLQRRT94F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxwFJRyIUiOvbVaVEVcJ8VzpPdwm_1FsY',
    appId: '1:1028662830128:android:b8ffd3376cfec51fb979f5',
    messagingSenderId: '1028662830128',
    projectId: 'app-explora-cdmx',
    storageBucket: 'app-explora-cdmx.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZ_DcHqcV_2JfpKJeQusixg2CQeb-q6s',
    appId: '1:1028662830128:ios:f75829f14c0a3845b979f5',
    messagingSenderId: '1028662830128',
    projectId: 'app-explora-cdmx',
    storageBucket: 'app-explora-cdmx.firebasestorage.app',
    androidClientId: '1028662830128-0bf98ejm0p6d5d995o8dlamp33jqnj2c.apps.googleusercontent.com',
    iosClientId: '1028662830128-2vhd94liqj5q3aovb29t3vubnb753vth.apps.googleusercontent.com',
    iosBundleId: 'com.urbenia.explora-cdmx',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGZ_DcHqcV_2JfpKJeQusixg2CQeb-q6s',
    appId: '1:1028662830128:ios:2f1e9aa7f02da9ceb979f5',
    messagingSenderId: '1028662830128',
    projectId: 'app-explora-cdmx',
    storageBucket: 'app-explora-cdmx.firebasestorage.app',
    iosBundleId: 'com.castilla.exploracdmx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1jIA3Uw6Nr0YZavhlqbGJll1Z_LyhR4',
    appId: '1:1028662830128:web:2ab7dd3b1d5fbb50b979f5',
    messagingSenderId: '1028662830128',
    projectId: 'app-explora-cdmx',
    authDomain: 'app-explora-cdmx.firebaseapp.com',
    storageBucket: 'app-explora-cdmx.firebasestorage.app',
    measurementId: 'G-8S16642LNB',
  );
}
